apiVersion: v1
kind: Service
metadata:
  name: blog-svc
  namespace: blog
spec:
  selector:
    role: app
  ports:
   - port: 8080
     nodePort: 30080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  labels:
    role: app
  namespace: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: app
        image: "docker-registry.scubbo.org:8843/scubbo/blog_nginx:built_in_ci"
        imagePullPolicy: 'Always'
        resources:
          requests:
            cpu: 10m
