baseURL = 'https://blog.scubbo.org/'
languageCode = 'en-us'
title = "Jack Jackson's Blog"
theme = "ananke"
disqusShortname = 'scubbo-blog'

SectionPagesMenu = "main"

[menu]
[[menu.main]]
  identifier = 'tags'
  name = 'Tags'
  url = '/tags/'

[params]
  twitter = "https://twitter.com/jacksquaredson"
  github = "https://github.com/scubbo"
  linkedin = "https://www.linkedin.com/in/jack-jackson-14a47441/"
  mastodon = "https://fosstodon.org/@scubbo"
  custom_css = ['inlinespoiler.css']
  show_reading_time = true
  page_source_base = "https://gitea.scubbo.org/scubbo/blogContent/src/branch/main/blog/"

# That is, explicitly disabling `categories` taxonomy
# https://gohugo.io/content-management/taxonomies/#example-removing-default-taxonomies
[taxonomies]
  tag = 'tags'

# https://gohugo.io/content-management/related/
# https://blog.scubbo.org/posts/tags-in-archetype/
# `includeNewer = true` => include pages that are newer than the current page in the "Related" sidebar
[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80
[[related.indices]]
  name = 'date'
  weight = 10

# https://roneo.org/en/hugo-custom-css-classes-images-markdown-attributes/
[markup.goldmark.parser.attribute]
block = true
title = true
