baseURL = 'https://blog.scubbo.org/'
languageCode = 'en-us'
title = "Jack Jackson's Blog"
theme = "ananke"
googleAnalytics = "UA-216020156-1"
disqusShortname = 'scubbo-blog'

SectionPagesMenu = "main"

[params]
  twitter = "https://twitter.com/jacksquaredson"
  github = "https://github.com/scubbo"
  linkedin = "https://www.linkedin.com/in/jack-jackson-14a47441/"
  custom_css = ['inlinespoiler.css']
  show_reading_time = true

# That is, explicitly disabling `categories` taxonomy
# https://gohugo.io/content-management/taxonomies/#example-removing-default-taxonomies
[taxonomies]
  tag = 'tags'
